### ISSUE TITLE
VecGeom crashes when constructing CMS Run4 geometry on GPU

### ISSUE THREAD

**Issue by mrguilima** [celeritas-project/celeritas#550] opened 2022-11-17 21:38 UTC
While trying to run demo-rasterizer on the CMS Run4 geometry (file cms-hllhc.gdml), the job throws this exception:
```=== Running: /work1/celeritas/lima/work/cele/build/app/demo-rasterizer input-cmsRun4-xyview.json
info: Loading VecGeom geometry from GDML at /work1/celeritas/common/gdml/cms-hllhc.gdml
status: Initializing tracking information
/work1/celeritas/lima/work/cele/app/demo-rasterizer/demo-rasterizer.cc:166: critical: caught exception: /work1/celeritas/lima/work/cele/src/celeritas/ext/VecgeomParams.cc:138:
celeritas: cuda error: cudaPeekAtLastError() failed:
    an illegal memory access was encountered
```

Using cuda-gdb to get some more info:
```
status: Initializing tracking information

CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x47d4800

Thread 1 "demo-rasterizer" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 21359, block (2,0,0), thread (0,0,0), device 0, sm 4, warp 2, lane 0]
0x00000000047d49d0 in void vecgeom::cuda::ConstructManyOnGpu_kernel<vecgeom::cuda::UnplacedPolyhedron, double, double, int, int, double const*, double const*, double const*>(unsigned long, vecgeom::cuda::UnplacedPolyhedron**, double const*, double const*, int const*, int const*, double const* const*, double const* const*, double const* const*)<<<(128,1,1),(32,1,1)>>> ()
```

**Comment by sethrj** [comment] 2022-11-17 21:47
Possibly fixed by https://gitlab.cern.ch/VecGeom/VecGeom/-/commit/68f8e149d29be378d7ff207bcd9c15d8ab71aba2

**Comment by mrguilima** [comment] 2022-11-17 21:58
The VecGeom tag used above was 4e083cd7, which was before this commit:
```
* 68f8e149 (9 weeks ago) Jonas Hahnfeld Rewrite PolyhedronStruct::Initialize without dynamic memory
```

Moving to current master (7a76ba3a), there is a different exception:
```
status: Initializing tracking information

CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x4de9da0

Thread 1 "demo-rasterizer" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 11, grid 22007, block (0,0,0), thread (0,0,0), device 0, sm 0, warp 0, lane 0]
0x0000000004de9f90 in void vecgeom::cuda::ConstructOnGpu<vecgeom::cuda::UnplacedSExtruVolume, int, double*, double*, double, double>(vecgeom::cuda::UnplacedSExtruVolume*, int, double*, double*, double, double)<<<(1,1,1),(1,1,1)>>> ()
(cuda-gdb)
```

**Comment by sethrj** [comment] 2022-11-21 14:50
Per the discussion with @hahnjo, we need to increase the *heap* size to fix this, not the per-thread *stack* size.

@mrguilima  could you please add a `set_cuda_heap_size` in `corecel/sys/Device.*` analogous to the `stack` function that's there, and check for a parameter `cuda_heap_size` in `demo-loop.cc` and `demo-rasterizer.cc` so that we can adjust it depending on the problem?

**Comment by hahnjo** [comment] 2022-11-21 15:47
> Possibly fixed by https://gitlab.cern.ch/VecGeom/VecGeom/-/commit/68f8e149d29be378d7ff207bcd9c15d8ab71aba2

Yes, this is the commit that reduces the problem, but as also [documented on the MR](https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/934#note_6007021) the problem is much, much bigger.

**Closed** 2022-11-22 03:54 UTC
Labels: bug, geometry
